### ISSUE TITLE
Error when try to log in nu account

### ISSUE THREAD

**Issue by Larision** [stefanreuther/c2ng#1]
Log showing:

_13:52:20 [main] <Info> [PCC2 v2.41 (c2ng)]
13:52:20 [main] <Debug> Starting GUI...
13:52:20 [gfx.sdl2] <Info> Video driver: direct3d, hw, target texture
13:52:20 [main] <Debug> Starting network...
13:52:20 [main] <Debug> Starting background thread...
13:52:20 [game.labels] <Error> -> onConnectionChange
13:52:20 [script] <Info> [PCC 2.41 (c2ng), core.q 2.40.13]
13:52:20 [main] <Debug> Initialisation complete
13:52:44 [game.nu] <Error> http://api.planets.nu/account/login?version=2: network access failed
13:52:44 [game.nu] <Error> Login failed_

version 2.40.13 logging ok

**Comment by stefanreuther** [comment]
Works for me in Linux, fails with the same error in Windows. I will look into it.

The difference between 2.40.13 and 2.41 is that the former are built with a MinGW compiler from 2005, whereas the latter are built with a much newer version.
